FROM  alpine

# MAINTAINER Thiago Nazario <thiago@nazario.com>

LABEL org.opencontainers.image.authors="Thiago Nazario"
LABEL org.opencontainers.image.description="Container image for https://github.com/opencontainers/image-spec" 
